### PR TITLE
Make black happy

### PR DESCRIPTION
**Pull request by joonhyungshin**
This fixes the linter error shown in jschneier#1427 to get it merged more quickly :)

### CODE REVIEW

**Comment by joonhyungshin** [comment]
This is just for reference: no need to merge. Feel free to make your own commit with the same changes.

**Review by Yohannes-B — APPROVED** [review]

**Comment by Yohannes-B** [comment]
Yes please merge. Didn't notice that there were more linter errors

**Comment by joonhyungshin** [comment]
@Yohannes-B Thanks! This is your own branch, so only you can merge this PR. Hope this gets released soon.

**Comment by yohannes15** [comment]
Its so confusing sometimes having a work and personal account haha

**Pull request merged**
